apiVersion: v1
kind: Service
metadata:
  name: {{ include "slowdns.fullname" . }}
  labels:
    {{- include "slowdns.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  clusterIPs:
  - {{ .Values.service.clusterIP }}
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.service.port }}
      port: 53
      protocol: TCP
      name: dns-tcp
    - targetPort: {{ .Values.service.port }}
      port: 53
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "slowdns.selectorLabels" . | nindent 4 }}
